### ISSUE TITLE
Find a Cloud Service to exchange Data

### ISSUE THREAD

**Issue by FabianKowatsch** [FabianKowatsch/Fusee#4]

**Comment by LksWllmnn** [comment]
## Google Drive from Lennard:
Lennard offered that the ProjectGroup can use some of the space from the Google Drive Account of his Family which got a space over 1TB

## BW- Cloud:
(description at: https://www.bw-cloud.org/de/erste_schritte)
After Registration (https://bw-cloud.org/q/regapp) there  is a waiting period, because an admin has to accept the registration. (my status at 09.04.21 8:52 AM was PENDING after 20 mins I was accepted).
After that you can set a password for the Service (after i clicked safe there was also a short waiting period before my passwort was accepted)

Next, I went to the Portal (portal.bw-cloud.org). there the username is the username from the hs and @hs-furtwangen.de (in my case for example willmanl@hs-furtwangen.de) and the password that I had set.
Now I added a “Datenträger”, but now I don’t know how to load any data on the cloud. 
And that’s my current status

**Comment by LksWllmnn** [comment]
Tried the connection over ssh and Putty, but couldn't log in somehow.

**Comment by LksWllmnn** [comment]
13.04.: new research Object: bwsyncandshare

**Comment by LksWllmnn** [comment]
Get the Desktop Client for your OS (https://customerupdates.nextcloud.com/kk1eoZCTo0kI5HpGE3IT/).
Or just use the Web Service (https://bwsyncandshare.kit.edu/)

Registration is pretty easy. As soon as you select the HFU you can connect with your HFU Account and start uploading files.

Total amount of space seems to be 50GB.

I can share the link to the MuVista Folder on the next meeting
